# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='has_working_schedule',
            field=models.BooleanField(default=False, verbose_name='Has working schedule'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
