# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oneauthtoken',
            table='one_authentication',
        ),
    ]
