# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 04:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionalWorkingDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('addDay', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyWorkingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(null=True)),
                ('month', models.IntegerField(null=True)),
                ('year', models.IntegerField(null=True)),
                ('schedule', models.CharField(max_length=500, null=True)),
                ('nextStartDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDefaultWorkingConstraint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sun_morning', models.BooleanField(default=False)),
                ('sun_evening', models.BooleanField(default=False)),
                ('mon', models.BooleanField(default=False)),
                ('tue', models.BooleanField(default=False)),
                ('wed', models.BooleanField(default=False)),
                ('thu', models.BooleanField(default=False)),
                ('fri', models.BooleanField(default=False)),
                ('sat', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalWorkingSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('personalSchedule', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('calendar', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='workingcalendar',
            unique_together=set([('year', 'month')]),
        ),
        migrations.AddField(
            model_name='personalworkingschedule',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.WorkingCalendar'),
        ),
        migrations.AddField(
            model_name='personalworkingschedule',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyworkingschedule',
            name='calendar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.WorkingCalendar'),
        ),
        migrations.AddField(
            model_name='monthlyworkingschedule',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='personalworkingschedule',
            unique_together=set([('user', 'month', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='monthlyworkingschedule',
            unique_together=set([('month', 'year')]),
        ),
        migrations.AlterUniqueTogether(
            name='exceptionalworkingday',
            unique_together=set([('user', 'date')]),
        ),
    ]
