# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20160718_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingcalendar',
            name='calendar',
            field=models.CharField(max_length=1000),
        ),
    ]
