# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20160802_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyworkingschedule',
            name='month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyworkingschedule',
            name='schedule',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyworkingschedule',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
