# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 14:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_auto_20160808_1736'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonalDefaultWorkingConstraint',
            new_name='PersonalDefaultWorkingRequest',
        ),
    ]
