# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-18 04:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(default=datetime.date(2016, 7, 18))),
                ('endDate', models.DateField(default=datetime.date(2016, 7, 18))),
                ('noLunch', models.BooleanField()),
                ('noWorking', models.BooleanField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='holiday',
            unique_together=set([('startDate', 'endDate')]),
        ),
    ]
