# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-20 02:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='endDate',
            field=models.DateField(default=datetime.date(2016, 7, 20)),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='startDate',
            field=models.DateField(default=datetime.date(2016, 7, 20)),
        ),
    ]
