# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 04:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0002_auto_20160720_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='endDate',
            field=models.DateField(default=datetime.date(2016, 8, 2)),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='startDate',
            field=models.DateField(default=datetime.date(2016, 8, 2)),
        ),
    ]
