# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-12 04:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0006_auto_20160811_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='endDate',
            field=models.DateField(default=datetime.date(2016, 8, 12)),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='startDate',
            field=models.DateField(default=datetime.date(2016, 8, 12)),
        ),
    ]
