# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-02 04:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0002_auto_20160720_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealprice',
            name='startDate',
            field=models.DateField(default=datetime.date(2016, 8, 2), unique=True),
        ),
        migrations.AlterField(
            model_name='monthcalendar',
            name='calendar',
            field=models.CharField(max_length=1000),
        ),
    ]
