# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-10 01:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0004_auto_20160808_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealprice',
            name='startDate',
            field=models.DateField(default=datetime.date(2016, 8, 10), unique=True),
        ),
    ]
