# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 01:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunch', '0005_auto_20160810_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealprice',
            name='startDate',
            field=models.DateField(default=datetime.date(2016, 8, 11), unique=True),
        ),
    ]
